name: BuildProduct

on:
  push:
    paths-ignore: 
      - 'docs/**'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build wxPython
    runs-on: macos-13
    if: github.repository_owner == 'laobamac'

    env:
      # GitHub Information
      branch: ${{ github.ref }}
      commiturl: ${{ github.event.head_commit.url }}${{ github.event.release.html_url }}
      commitdate: ${{ github.event.head_commit.timestamp }}${{ github.event.release.published_at }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install -r requirements.txt

      - name: Force Universal2 charset for Python
        run: |
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip uninstall -y charset_normalizer
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip download --platform macosx_10_9_universal2 --only-binary=:all: charset-normalizer
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install charset_normalizer-*-macosx_10_9_universal2.whl

      - name: Prepare Assets (--prepare-assets)
        run: >
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 Build-Project.command
          --run-as-individual-steps --reset-dmg-cache
          --prepare-assets

      - name: Prepare Application (--prepare-application)
        run: >
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 Build-Project.command
          --reset-pyinstaller-cache
          --run-as-individual-steps
          --prepare-application

      - name: Prepare Package (--prepare-package)
        run: >
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 Build-Project.command
          --prepare-package

      - name: Prepare Update Shim (--prepare-shim)
        run: >
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 Build-Project.command
          --run-as-individual-steps
          --prepare-shim

      - name: Prepare App for Upload
        run: |
          zip -r ./dist/OCLP-Mod.zip -j ./dist/OCLP-Mod.app
          /bin/mv ./dist/OCLP-Mod.zip ./OCLP-Mod.app.zip

      - name: Upload App to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenCore-Patcher.app (GUI)
          path: OCLP-Mod.app.zip

      - name: Upload AutoPkg Package to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AutoPkg-Assets.pkg
          path: ./dist/AutoPkg-Assets.pkg

      - name: Upload Installation Package to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenCore-Patcher.pkg
          path: ./dist/OCLP-Mod.pkg

      - name: Upload Uninstaller Package to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenCore-Patcher-Uninstaller.pkg
          path: ./dist/OCLP-Mod-Uninstaller.pkg

      - name: Upload Binary to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: OCLP-Mod.app.zip
          tag: ${{ github.ref }}
          file_glob: true

      - name: Upload AutoPkg Package to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/AutoPkg-Assets.pkg
          tag: ${{ github.ref }}
          file_glob: true

      - name: Upload Installation Package to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/OCLP-Mod.pkg
          tag: ${{ github.ref }}
          file_glob: true

      - name: Upload Uninstaller Package to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/OCLP-Mod-Uninstaller.pkg
          tag: ${{ github.ref }}
          file_glob: true
