name: Validate

on:
  push:
    paths-ignore: 
      - 'docs/**'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Validate
    runs-on: macos-latest
    if: github.repository_owner == 'laobamac'
    steps:
      - uses: actions/checkout@v4
      - name: Validate
        run: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 OCLP-Mod.command --validate
