name: Validate

on:
  push:
    paths-ignore: 
      - 'docs/**'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Validate
    runs-on: macos-13
    if: github.repository_owner == 'laobamac'
    steps:
      - uses: actions/checkout@v4
      - name: Validate
        run: |
          pip3 install -r requirements.txt
          pip3 install packaging
          aria2c -x 12 https://github.com/dortania/PatcherSupportPkg/releases/download/1.9.1/Universal-Binaries.dmg
          /Library/Frameworks/Python.framework/Versions/3.13/bin/python3 OCLP-Mod-GUI.command --validate
    
